name: goreleaser

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.5'
          cache: true
      - name: Set up Environment
        run: |
          echo "GOVERSION=$(go version|awk '{print $3}')" >> $GITHUB_ENV
      - name: Set up Snapcraft
        # HACK: the mkdirs are  a hack for https://bugs.launchpad.net/snapcraft/+bug/1889741
        run: |
          sudo snap install --classic snapcraft
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      # - name: Cache Go modules
      #   uses: actions/cache@v2.1.4
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-
      - name: Snapcraft Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_LOGIN_KEY }}
        run: |
          snapcraft login
      - name: Docker Login
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      - name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json